### ISSUE TITLE
Upgrade to Request-Promise 0.3.x

### ISSUE THREAD

**Issue by analog-nico** [chovy/shapeshift#2]
Hi @anthonyettinger 

Out of curiosity I checked your code to see if you are affected by braking changes. And yes, you probably want to do a small change once you update Request-Promise.

Change these lines:

``` js
    return requestp(_.extend(defaults, opts, {
        url: url
    }));
```

... to:

``` js
    return requestp(_.extend(defaults, opts, {
        url: url
    })).promise(); // Added
```

This is not required but I would recommend it in your case. See the [migration instructions](https://github.com/tyabonil/request-promise#migrating-from-02x-to-03x) for details.

---

Since version 0.3.0 Request-Promise is 100% compatible with Request. This means you can also apply a callback - even use a callback and a promise at the same time. ;) Anyway, I saw your todo which you could implement like this:

``` js
var requestp = require('request-promise');

var shapeshift = module.exports = {};
var url = 'http://shapeshift.io';

requestpWithDefaults = requestp.defaults({
    json: true,
    resolveWithFullResponse: true
});

// get( [uri], [options], [callback] ) - same signature as Request would provide
function get() {
    return requestpWithDefaults.apply(null, arguments).promise();
}

shapeshift.getRate = function(pair, callback){
    return get(url + '/rate/' + pair, callback);
};

shapeshift.getLimit = function(pair, callback){
    return get(url + '/limit/' + pair, callback);
};
```

Now a user can call your library in two ways:

``` js
var shapeshift = require('shapeshift');

// Use a callback as you would with Request
shapeshift.getRate('btc_ltc', function (err, response, body) {
    // ...
});

// Use the promise as you already do
shapeshift.getRate('btc_ltc')
    .then(function (data) {
      // ...
    });
```

Cheers,
Nico

**Comment by ralyodio** [comment]
Is this still an issue? I just upgraded all the dependencies and tests passed fine. I dont' recall ever having to use `.promise()` with request-promise and I use it on all my projects

**Comment by analog-nico** [comment]
I would say, just ignore it. I guess you and your users use `.then(...)` all the time and not any special Bluebird methods like `.bind(...)` directly after the shapeshift call.

``` js
// Works
shapeshift.getRate(pair)
    .then(function(data){
        //do something w/ data
    });

// Does not work
shapeshift.getRate(pair)
    .bind(context)                 // <---
    .then(function(data){
        //do something w/ data
    });

// Works again
shapeshift.getRate(pair)
    .promise()                     // <---
    .bind(context)
    .then(function(data){
        //do something w/ data
    });
```

**Comment by ralyodio** [comment]
I don't use bluebird. I haven't tried calling bind against a request object -- I can see if there's a way to do it. But it looks like you found a way already.

You should be able to do this:

```
shapeshift.getRate(pair).then(callback.bind(ctx));
```

I'm not sure why you would want to change the context of the shapeshift module's functions. I usually only ever need to change it for the callback.

**Comment by analog-nico** [comment]
Sorry for the misunderstanding. I am not using your lib. Back in 2014 I just wanted to make sure that the breaking changes I introduced in Request-Promise don't surprise you.

**Comment by ralyodio** [comment]
Oh cool. Didn't realize you were the author of that module. Its an awesome module by the way. Good job.
